name: Node CI from travis.yml

# the below will run on any PR
#on: [push]
# the below only runs when merging to the specified branches 
on:
  pull_request:
    branches:    
      - master         # Push events on master branch
      - 'release/*'   # Push events to branches matching refs/heads/releases/*

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10]
      fail-fast: true
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        fetch-depth: 1
    - name: npm uninstall, install
      run: |
        npm uninstall typescript --no-save
        npm install
      env:
        workerCount: 3
        timeout: 600000
        
